name: Simple Node.js Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    - name: Create and run test
      run: |
        echo "console.log('Test passed!');" > test.js
        node test.js